[#1076] Keychain claims no data exist and data exist at the same time
Electric-Coin-Company/zashi-ios pull request #1079
Opened 2024-02-21 13:09 UTC by LukasKorba

Closes #1076

- The Queries and Uniqueness Constraints changed with the `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly` flag, we are forced to provide account now.
- Implication of this change is that fingerprint of stored wallet changed so everyone will face a downside of this change - Zashi will start with create/restore wallet.
- The migration of previously stored wallet is unfortunately not possible because the previous wallet can't be read - that is definition of this ticket and bug described.
- With the new fixes, all keychain and sec item tests pass.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Does the code abide by the [Coding Guidelines](../blob/main/docs/CODING_GUIDELINES.md)?
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/main/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place. [Learn More...](../blob/main/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), [LICENSE.md](../blob/main/LICENSE.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

2024-02-21 20:45 UTC, LukasKorba commented
The problem we face is about Uniqueness of queries. Please read more [here](https://developer.apple.com/forums/thread/724013)

In a nutshell, the keys used for the accessibility are defined as
```
@available(iOS 4.0, *)
public let kSecAttrAccessibleWhenUnlockedThisDeviceOnly: CFString

@available(iOS 4.0, *)
public let kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly: CFString
```

Those strings are unique for every key used, the final fingerprint for read/write operation vary depending on these + all other keys set by devs (some of the keys don't play a role in Uniqueness btw but most do).

2024-02-23 23:10 UTC, pacu commented
> The problem we face is about Uniqueness of queries. Please read more [here](https://developer.apple.com/forums/thread/724013)

I'll read this section on Halloween  👻 🥶
<img width="1112" alt="image" src="https://github.com/Electric-Coin-Company/zashi-ios/assets/484008/1d12f91c-9827-41b6-9c3a-0908d17eee1a">

2024-02-24 13:33 UTC, daira commented
> Implication of this change is that fingerprint of stored wallet changed so everyone will face a downside of this change - Zashi will start with create/restore wallet.

Is the description still accurate? I thought we'd fixed that problem.

(Note that the first comment on a GitHub PR is used for the commit message, so in general it's important that it be accurate to avoid later confusion. If a limitation has been fixed, make sure to edit the first comment, even if later comments in the PR explain the fix.)

2024-02-24 13:39 UTC, daira commented on modules/Sources/Dependencies/WalletStorage/WalletStorage.swift
> +        account: String
After we change the Queries and Uniqueness Constraints, does that leave sensitive data around under the old keys even if the user nukes the wallet?

2024-02-24 13:53 UTC, daira requested changes
NACK because I don't think this is independently reviewable as-is.

2024-02-27 07:14 UTC, LukasKorba commented
@daira has brought a very interesting point on the table - what to do with the keychain setup and `kSecAttrAccount` for multiple users of the same Zashi. That is something that hasn't been solved yet. Closing the PR for now

2024-02-27 07:14 UTC, closed without merging